### PR TITLE
Deindent and a few more examples

### PR DESCRIPTION
**Pull request by joehand**
Run `node example/nested.js` to see how the newline can break nested strings. We nest a lot in the dat CLI so this breaks it. 

Is there a reason we need to add a newline?

### CODE REVIEW

**Comment by joehand** [comment]
Update:

* Added `deindent` function. 
* Trim now runs `deindent` then `trim()` on the string (@mafintosh is that what you were thinking?)
* Added a **buggy** example with `process.exit`

## Bug w/ Exit

The bug was not chalk related, it was related to updating text after `SIGINT` and before exit. Is there a better way to do this? Or is there a bug in how diffy is handling this?

**Comment by mafintosh** [comment]
Got around to this finally :) Does the deindent trim the first newline? Or does it simply deindent all the lines?

**Comment by joehand** [comment]
> Or does it simply deindent all the lines?

Yes, just deindents, no trimming. (see `node examples/date-deindent.js`) It turns this:

```js
diffy.render(function () {
  return deindent(`
    Hello user. The time is:
      ${new Date()}
    That is all for now
  `)
})
```

Into:

```

Hello user. The time is:
  Thu Mar 29 2018 08:35:38 GMT-0700 (PDT)
That is all for now

```

**Comment by mafintosh** [comment]
@joehand hmm yea that isn't really that useful. guess i can just use trim + '\n' instead

**Comment by joehand** [comment]
> @joehand hmm yea that isn't really that useful. guess i can just use trim + '\n' instead

haha ya, I'm fine trimming the space at the top of deindent but just makes it a bit more confusing. Or we can make an `opinionatedTrim` function =).

**Comment by mafintosh** [comment]
@joehand let's just remove deindent and keep your changes. sorry for going back and forth

**Comment by joehand** [comment]
No problem. Updated. 

@mafintosh realized the bug I'm seeing on exit is caused by the `SIGINT` changing the output and diffy not catching it? If I type in other random things, it moves the new content further off:

screen shot 2018-03-29 at 9 44 08 am

screen shot 2018-03-29 at 9 44 13 am

**Comment by mafintosh** [comment]
@joehand try using the input module. that might fix it by capturing the input for you. i'll try myself

**Comment by mafintosh** [comment]
@joehand yea adding require('../input')() to your example fixes it for me. In the render function use https://github.com/mafintosh/diffy/blob/master/index.js#L18 to see if it is destroyed (exited) and print your exit message :) - I'm all for making that flow easier if you have API ideas

**Pull request merged**
